# Generated by Django 3.1.6 on 2021-03-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mainPageProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ürün adı')),
                ('desc', models.TextField(verbose_name='Ürün açıklaması')),
                ('category', models.CharField(default='sweatshirt', max_length=50, verbose_name='Ürün kategorisi')),
                ('image', models.CharField(max_length=50, verbose_name='Ürün resmi')),
                ('isPublished', models.BooleanField(default=True)),
            ],
        ),
    ]
