# Generated by Django 3.1.6 on 2021-03-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpageproduct',
            name='link',
            field=models.URLField(default='link giriniz', max_length=500, verbose_name='Ürün linki'),
        ),
    ]
