# Generated by Django 3.1.6 on 2021-03-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_mainpageproduct_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpageproduct',
            name='reebzLink',
            field=models.URLField(default='Reebz ürün sayfa linki giriniz', max_length=500, verbose_name='Reebz Ürün linki'),
        ),
        migrations.AlterField(
            model_name='mainpageproduct',
            name='link',
            field=models.URLField(default='link giriniz', max_length=500, verbose_name='Shopier Ürün linki'),
        ),
    ]
