# Generated by Django 3.1.6 on 2021-03-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210320_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpageproduct',
            name='desc',
            field=models.CharField(max_length=50, verbose_name='Ürün fiyatı'),
        ),
    ]
