# Generated by Django 3.1.6 on 2021-03-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210323_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpageproduct',
            name='image',
            field=models.ImageField(default='Büyük resmi ekleyiniz', upload_to='uploads/'),
        ),
    ]
