# Generated by Django 3.1.6 on 2021-03-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210324_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpageproduct',
            name='image',
            field=models.CharField(max_length=50, verbose_name='Ürün resmi adı'),
        ),
    ]
