# Generated by Django 3.1.6 on 2021-03-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210324_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpageproduct',
            name='newImage',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Yeni resim yüklemek için tıklayınız'),
        ),
    ]
