# Generated by Django 3.1.6 on 2021-03-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210318_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isPublished',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='sweatshirt', max_length=50, verbose_name='Ürün kategorisi'),
        ),
    ]
