# Generated by Django 3.1.6 on 2021-03-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210318_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img1',
            field=models.CharField(default='resim1', max_length=50, verbose_name='küçük resim 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='img2',
            field=models.CharField(default='resim2', max_length=50, verbose_name='küçük resim 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='img3',
            field=models.CharField(default='resim3', max_length=50, verbose_name='küçük resim 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='img4',
            field=models.CharField(default='resim4', max_length=50, verbose_name='küçük resim 4'),
        ),
    ]
