# Generated by Django 3.1.6 on 2021-03-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210320_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.TextField(default='url linki giriniz', verbose_name='Ürün linki'),
        ),
    ]
