# Generated by Django 3.1.6 on 2021-03-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(max_length=500, verbose_name='Ürün linki'),
        ),
    ]
