# Generated by Django 3.1.6 on 2021-03-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210320_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(default='link giriniz', max_length=500, verbose_name='Shopier Ürün linki'),
        ),
    ]
