# Generated by Django 3.1.6 on 2021-03-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210320_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='extraProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ürün adı')),
                ('desc', models.CharField(max_length=20, verbose_name='Ürün Fiyatı')),
                ('image', models.CharField(max_length=50, verbose_name='Ürün resmi')),
                ('link', models.URLField(default='link giriniz', max_length=500, verbose_name='Shopier Ürün linki')),
                ('reebzLink', models.URLField(default='Reebz ürün sayfa linki giriniz', max_length=500, verbose_name='Reebz Ürün linki')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(max_length=20, verbose_name='Ürün Fiyatı'),
        ),
    ]
