# Generated by Django 3.1.6 on 2021-03-23 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_ispublished'),
    ]

    operations = [
        migrations.DeleteModel(
            name='extraProduct',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
