# Generated by Django 3.1.6 on 2021-03-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210323_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ürün adı')),
                ('desc', models.CharField(max_length=50, verbose_name='Ürün fiyatı')),
                ('image', models.CharField(max_length=50, verbose_name='Ürün resmi')),
                ('link', models.URLField(default='link giriniz', max_length=500, verbose_name='Shopier Ürün linki')),
                ('reebzLink', models.URLField(default='Reebz ürün sayfa linki giriniz', max_length=500, verbose_name='Reebz Ürün linki')),
            ],
        ),
    ]
