# Generated by Django 3.1.6 on 2021-03-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_similarproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='similarproduct',
            name='img',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
