# Generated by Django 3.1.6 on 2021-03-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_similarproduct_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similarproduct',
            name='img',
            field=models.ImageField(default='resim ekleyiniz', upload_to='uploads/'),
        ),
    ]
