# Generated by Django 3.1.6 on 2021-03-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210324_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='Büyük resmi ekleyiniz', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img1',
            field=models.ImageField(default='küçük resim ekleyiniz', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img2',
            field=models.ImageField(default='küçük resim ekleyiniz', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img3',
            field=models.ImageField(default='küçük resim ekleyiniz', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img4',
            field=models.ImageField(default='küçük resim ekleyiniz', upload_to='uploads/'),
        ),
    ]
