# Generated by Django 3.1.6 on 2021-03-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210324_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='newImage',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Yeni resim yüklemek için tıklayınız'),
        ),
        migrations.AddField(
            model_name='similarproduct',
            name='newImage',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Yeni resim yüklemek için tıklayınız'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=50, verbose_name='Ürün resmi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img1',
            field=models.CharField(default='resim1', max_length=50, verbose_name='küçük resim 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img2',
            field=models.CharField(default='resim2', max_length=50, verbose_name='küçük resim 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img3',
            field=models.CharField(default='resim3', max_length=50, verbose_name='küçük resim 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img4',
            field=models.CharField(default='resim4', max_length=50, verbose_name='küçük resim 4'),
        ),
        migrations.AlterField(
            model_name='similarproduct',
            name='img',
            field=models.ImageField(default='resim k', upload_to='uploads/'),
        ),
    ]
